[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD ./dondondonuts-cms/"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "_site"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[template.environment]
  META_API_ACCESS_TOKEN = "Your Meta API Access Token"
  META_PIXEL_ID = "Your Meta Pixel ID"
  TIKTOK_API_ACCESS_TOKEN = "Your TikTok API Access Token"
  TIKTOK_PIXEL_ID = "Your TikTok Pixel ID"